### PR TITLE
feat: use `local-pkg` to avoid using `__dirname` on `esm` env

### LINKED ISSUE #79: [Bug] shipped `.mjs` bundle includes reference to `__dirname`
`__dirname` is not available in ES modules.
Had to switch my project to ESM for another dependency and this came up as an error.
I'm not clear on how files are handled, but maybe it's not respecting the
```json
"exports": {
    ".": {
      "import": "./index.mjs",
      "require": "./index.cjs"
    },
    "./*": "./*"
  },
```
from the `package.json` of auto-imported modules

### PR DESCRIPTION
**Pull request by userquin**
close #79

### CODE REVIEW

**Comment by userquin** [comment]
We need to change the tests

**Comment by antfu** [comment]
Just do a // @ts-ignore there would work I think

**Comment by userquin** [comment]
> 

testing...

**Comment by userquin** [comment]
@antfu with `// @ts-ignore` we remove:
```bash
error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'
```
error, but then, running it we get 
```bash
SyntaxError: Cannot use 'import.meta' outside a module
```
so we need to split the tests.

**Review by antfu — APPROVED** [review]

**Pull request merged**
