### PR TITLE
feat: add recoil preset

### PR DESCRIPTION
**Pull request by Enside**
add recoil preset

### CODE REVIEW

**Comment by userquin** [comment]
you should also add it here: https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/index.ts

**Comment by Enside** [comment]
> you should also add it here: https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/index.ts

Ok, added now

**Comment by userquin** [comment]
> > you should also add it here: https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/index.ts
> 
> Ok, added now

can you run the lint script on your local? it seems weird changing the record keys

**Comment by userquin** [comment]
@Enside can you provide some links where these functions can be found? for example, add it as a coment on the recoil module

**Comment by userquin** [comment]
@Enside somehting like this: https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/quasar.ts#L5

**Comment by Enside** [comment]
> @Enside somehting like this: https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/quasar.ts#L5

thanks, comment added and run lint

**Comment by userquin** [comment]
@Enside maybe you can add missing entries like `isRecoilValue`, useRecoilCallback` and `Misc` package: `useRecoilStoreID`.

I don't know if the `Utils` package can also be added (`_UNSTABLE` entries, maybe something wrong in docs or method have those names?)

**Comment by Enside** [comment]
> @Enside maybe you can add missing entries like `isRecoilValue`, `useRecoilCallback` and `Misc` package: `useRecoilStoreID`.
> 
> I don't know if the `Utils` package can also be added (`_UNSTABLE` entries, maybe something wrong in docs or methods have those names?)
> 
> for example: `useRecoilTransaction_UNSTABLE`

api prefixed with `_UNSTABLE` is likely going to be removed in future versions. I'll add `isRecoilValue` and `useRecoilCallback` to the list, but the rest of api may cause naming conflict and is not that commonly used.

**Review by antfu — APPROVED** [review]

**Review by userquin — APPROVED** [review]

**Comment by omnjpa27516** [comment]
@Enside Could you please add some presets? I don't know how to use Git...

1. https://www.npmjs.com/package/petite-vue-i18n
```
import type { ImportsMap } from '../types'

export default <ImportsMap>({
  'vue-i18n': [
    'createI18n',
    'useI18n',
  ],
})
```

2. https://github.com/axios/axios
```
import type { ImportsMap } from '../types'

export default <ImportsMap>({
  'axios': [
    ['default', 'axios'],
  ],
})
```

**Comment by Enside** [comment]
> @Enside Could you please add some presets? I don't know how to use Git...
> 
> 1. https://www.npmjs.com/package/petite-vue-i18n
> 
> ```
> import type { ImportsMap } from '../types'
> 
> export default <ImportsMap>({
>   'petite-vue-i18n': [
>     'createI18n',
>     'useI18n',
>   ],
> })
> ```
> 
> 2. https://github.com/axios/axios
> 
> ```
> import type { ImportsMap } from '../types'
> 
> export default <ImportsMap>({
>   'axios': [
>     ['default', 'axios'],
>   ],
> })
> ```

ok I'll try, but I don't know if it's necessary to import default from `axios` globally.

**Comment by omnjpa27516** [comment]
> ok I'll try, but I don't know if it's necessary to import default from `axios` globally.
Thank you. It's from https://github.com/antfu/unplugin-auto-import/issues/48#issuecomment-932794376

**Pull request merged**
