### PR TITLE
feat: support tsx, jsx by default and add option `defaultExportByFilename`

### PR DESCRIPTION
**Pull request by niku98**
### Description

~~Add support for React Component as an option.~~

**Updated:**
- Support tsx, jsx by default
- Add option `defaultExportByFilename`:  boolean
  - When `true`, use file name as default export's alias

### Linked Issues
 #268

### Additional context

No.

### CODE REVIEW

**Comment by antfu** [comment]
I'd prefer to keep this plugin framework-agnostic. I think including `tsx` and `jsx` by default sounds reasonable. We might use need the option named `defaultExportByFilename` to include default exports for your case.

**Comment by niku98** [comment]
> I'd prefer to keep this plugin framework-agnostic. I think including `tsx` and `jsx` by default sounds reasonable. We might use need the option named `defaultExportByFilename` to include default exports for your case.

This sounds good, hope that it will be shipped soon.

**Comment by antfu** [comment]
You could push changes directly to this branch if you want to work on that

**Comment by niku98** [comment]
> You could push changes directly to this branch if you want to work on that

Oh, yes. Let's me try

**Comment by niku98** [comment]
@antfu Hi, I have pushed for a while. Can u review and merge if it is ok?

**Pull request merged**
