### PR TITLE
feat: support `sideEffects` in resolver, close #75

### LINKED ISSUE #75: How to auto import ant design vue component and styles in tsx or jsx?
tsx component
```js
export default defineComponent({
// ...
  setup(props, { attrs }) {
  // ...
    return (): JSX.Element => {
      return <Input {...attrs} />
    }
  },
})
```

vue.config.js
```js
const Components = require('unplugin-vue-components/webpack')
const AutoImport = require('unplugin-auto-import/webpack')

module.exports = {
  // ...
  configureWebpack: {
    plugins: [
      Components({
        resolvers: [
          resolvers.AntDesignVueResolver({
            resolveIcons: true,
            importStyle: 'less',
          })
        ]
      }),

      // How to set ?
      AutoImport({
        include: [
          /\.[tj]sx?$/,
        ],
        imports: [],
        resolvers: (name) => {
          console.log(name)
        }
      })
    ]
  }
}

```

### PR DESCRIPTION
**Pull request by sxzz**

### CODE REVIEW

**Comment by sxzz** [comment]
fix #75

**Comment by sxzz** [comment]
The resolvers of `unplugin-auto-import` and `unplugin-vue-components` are not compatible, we can make their interfaces consistent.

**Comment by sxzz** [comment]
@antfu So, do we add some resolvers like `unplugin-vue-components` to this plugin or we change resolvers of two plugins to the same interface? WDYT?

**Comment by antfu** [comment]
Yeah I think we should make them align.

**Comment by sxzz** [comment]
If we do this, it is a breaking change.

**Comment by antfu** [comment]
I don't mind breaking changes - it won't affect many users either I assume

**Pull request merged**
