### PR TITLE
fix: write file to be sync

### PR DESCRIPTION
**Pull request by lishaobos**
## options.cache

while writeFfile is not sync,  cache.json will be messy.

### CODE REVIEW

**Comment by antfu** [comment]
Can you share more context? I think we are awaiting them, it shouldn't affect much

**Comment by lishaobos** [comment]
> Can you share more context? I think we are awaiting them, it shouldn't affect much

if i dont use async write cache file

image

**Comment by lishaobos** [comment]
or write a new function, only write file sync on cache

> Can you share more context? I think we are awaiting them, it shouldn't affect much

or write a new function, only sync write file on cache

**Comment by lishaobos** [comment]
i have an another idea, beat performance!

**Pull request closed without merging**
